site_name: QGIS pro začátečníky
site_url:  https://gismentors.github.io/qgis-zacatecnik/
docs_dir:  docs
theme: 
  name: material
  language: cs
  features:
    - content.code.copy
    - navigation.footer
  palette:
    primary: yellow
copyright: Copyright &copy; 2014-2025 GISMentors
use_directory_urls: false
nav:
  - intro/index.md
  - vektorova_data/index.md
  - rastrova_data/index.md
  - webove_sluzby/index.md
  - mapovy_vystup/index.md
  - ruzne/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption  
plugins:
  - glightbox
  - search
  - macros
extra:
  wikipedia: https://cs.wikipedia.org/wiki
  skoleni: https://gismentors.github.io
  rarr: →
